### ISSUE TITLE
Errors when running npm run ios

### ISSUE THREAD

**Issue by ricardogomez-dev** [salmonco/react-native-radar-chart#3]
I'm having these errors when I run npm run ios. If I remove the component that is using this library it works perfectly, then after already having the app running I added again the component using this library and it works now, but it doesn't work on first load for some reason. These are the errors:

<img width="1440" alt="Screenshot 2024-07-11 at 9 11 50 a m" src="https://github.com/salmonco/react-native-radar-chart/assets/56089763/233fd240-78d0-4d1c-9261-906388d815cf">

**Comment by ricardogomez-dev** [comment]
I think this is because of Expo compatibility, I'm using Expo on my project.

**Comment by ricardogomez-dev** [comment]
This is expo compatibility issue, any solution?

**Comment by salmonco** [comment]
Sorry for the late reply.
I just created a new expo project, installed the library, and tested it, but the above error did not occur.
If you can send me your project code, I can get a clone and check it out. thank you.

**Comment by caiopratali** [comment]
same error here
<img width="1193" alt="Captura de Tela 2024-10-02 às 18 56 40" src="https://github.com/user-attachments/assets/ff1ec6ce-9e13-4e44-a23d-80f0fe544092">

**Comment by salmonco** [comment]
Hello,
If possible, please provide project code that I can clone. I would like to run and test the project to determine its relationship with the library.

**Comment by caiopratali** [comment]
> Hello, If possible, please provide project code that I can clone. I would like to run and test the project to determine its relationship with the library.

Project link for you to debug:
https://github.com/caiopratali/radar-chart-with-expo

**Comment by caiopratali** [comment]
When placing the lib code locally it worked, it must be some configuration, but I don't know how to debug the lib...

**Comment by caiopratali** [comment]
update: There is an error on Android too

**Comment by salmonco** [comment]
Hello, thank you very much for providing the code. The error was a dependency conflict between the project and the library.

By placing the library's `react` and `react-native` dependencies in `peerDependency` instead of `dependencies` in `package.json`, no dependency conflicts occurred, which was resolved in version `0.0.26`.

For reference, `peerDependency` allows projects to use instances that are already installed, avoiding version conflicts or duplication issues.
