### ISSUE TITLE
The chart doesn't work for bigger numbers

### ISSUE THREAD

**Issue by ricardogomez-dev** [salmonco/react-native-radar-chart#4]
If I add bigger numbers like thousands the stroke is out of the chart, for this example i'm using hundreds 100,200,300

<img width="321" alt="Screenshot 2024-07-11 at 9 27 03 a m" src="https://github.com/salmonco/react-native-radar-chart/assets/56089763/c81e08f4-23ff-4fe8-a23c-4b9e496a768d">

**Comment by salmonco** [comment]
Thank you for opening the issue.
As you mentioned, we modified it so that if the data value is greater than 100, it does not go off the chart. 5b512f7f44cdd2d15ee19cdce7f2bc08ad62b592
This is reflected in the latest version of the library.

**Comment by ricardogomez-dev** [comment]
Thank you so much!! This is working properly now 

<img width="365" alt="Screenshot 2024-07-13 at 9 15 02 a m" src="https://github.com/user-attachments/assets/5d9bce02-ff09-44fc-9b2e-9c2e646234c2">
