### ISSUE TITLE
isCircle prop doesn't work

### ISSUE THREAD

**Issue by ricardogomez-dev** [salmonco/react-native-radar-chart#5]
The chart is circular even if the docs says that default value is false. Also the prop doesn't work

<img width="1020" alt="Screenshot 2024-07-11 at 9 33 34 a m" src="https://github.com/salmonco/react-native-radar-chart/assets/56089763/09b8afd2-9867-41c1-84e8-7066c32deb0b">

**Comment by salmonco** [comment]
Thank you for opening the issue.
It is said that the error `does not exist on type ‘IntrinsicAttributes’` usually occurs when TypeScript does not recognize the props type of a component. To resolve this error, we added code that exports the `RadarChartProps` type to the library. 8733942363a17228a900554e72c7d59138a14ac3

**Comment by ricardogomez-dev** [comment]
Thank you so much!! This issue is fixed as well, you are awesome!!
