### ISSUE TITLE
Labels too close to the chart

### ISSUE THREAD

**Issue by FirePlank** [salmonco/react-native-radar-chart#7]
Hello,

I am experiencing an issue where the labels are too close to the chart such that the text is clipping into the chart. There is enough view space for the text to be further apart but for some reason it doesn't do that. I also didn't find any way to change the label distance from the chart in the docs. Please add this option.
![image](https://github.com/user-attachments/assets/0a923819-125c-4035-bb8c-0d49e6101351)

**Comment by salmonco** [comment]
Hello, Thank you for opening the issue.

Added `labelDistance` prop to adjust the distance between labels and charts. Additionally, by adding the `scale` prop, you can adjust the size of the chart so that labels are not cut off within size.

**Comment by FirePlank** [comment]
Thank you for the quick update!

**Comment by FirePlank** [comment]
I updated the package and the label distance is unaffected by the labeldistance property for some reason. Any reason why?

**Comment by salmonco** [comment]
I forgot to build it. I published again. Thank you.
