### ISSUE TITLE
Odd data number causes division lines to duplicate

### ISSUE THREAD

**Issue by jahvi** [salmonco/react-native-radar-chart#8]
When using an odd number of data points the number of division lines get duplicated, eg:

**3 data points: (incorrect)**
![Screenshot 2024-09-29 at 12 54 00](https://github.com/user-attachments/assets/6a9fc9e0-ac32-475d-a83f-3e779664691f)

**4 data points: (correct)**
![Screenshot 2024-09-29 at 12 54 26](https://github.com/user-attachments/assets/36ba6138-2c99-41c2-b6c6-ed72ca98c704)

**Comment by salmonco** [comment]
Hello, Thank you for opening the issue.

I set up the axes to match the number of data and deployed it in the latest version `0.0.17`.

Additionally, the axis of the first data was set to be centered. thank you.

**Comment by jahvi** [comment]
Great, thanks for sorting so quickly!
