### ISSUE TITLE
Is it possible to set the graph max value manually?

### ISSUE THREAD

**Issue by jahvi** [salmonco/react-native-radar-chart#9]
Can the max value be set manually as part of the graph config? I'm trying to get my graph to render similarly to the ones in the readme but looking at the code it seems like the max value is set based on the max value of the data passed so you will always end up with a value that will reach all the way to the edge of the graph. Is there a workaround for this? 

![Screenshot 2024-09-29 at 17 23 28](https://github.com/user-attachments/assets/bc19d314-fba8-4836-8272-ed3a14a6c845)

**Comment by salmonco** [comment]
The `maxValue` prop was added to version `0.0.18`.

README.md has also been updated. thank you.

**Comment by jahvi** [comment]
This is perfect thanks!
